HOST = "127.0.0.1"
USER = "root"
PASSWORD = "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"
#REMEBER TO ADD YOUR OWN PASSWORD HERE!!! AND INCLUDE IN GIT IGNORE SO THAT NO SENSITIVE INFO IS SHARED!!